### ISSUE TITLE
Declarative way of using a standard action with @ActionType as window action

### ISSUE THREAD

**Issue by belyaev-andrey** [cuba-platform/cuba#3022] opened 2020-09-02 11:08 UTC
When adding a "runReport" action to a screen, there is no possibility to specify it on the screen level. See the project attached, `department-browse.xml` file, lines `26-28`

When adding this action to a component level (see the same file, line `48`), the run report window shows only reports with the input parameter of a component's entity type. But the screen `department-browse` is allowed to run all reports defined in the application.

STR:
* Deploy the project and import reports attached
* Try to run report using "Run All Reports" button

ER:
* You should see reports running screen with all reports (for departments and employees)

AR: 
* The button doesn't work.  

Please note that programmatic way works fine, see `DepartmentBrowse.java` file, lines `25-29`

[hr.zip](https://github.com/cuba-platform/cuba/files/5161836/hr.zip)
[Reports.zip](https://github.com/cuba-platform/cuba/files/5161838/Reports.zip)

**Comment by glebfox** [comment] 2021-03-01 08:14
Hi @belyaev-andrey 

> When adding this action to a component level (see the same file, line 48), the run report window shows only reports with the input parameter of a component's entity type. But the screen department-browse is allowed to run all reports defined in the application.

This is by design. Since the `RunReportAction` extends `ListAction` it has the `target` attribute. When an action is defined in XML this attribute is set by a loader. 

If you alter the mentioned code like this:

```
RunReportAction runAllReportsAction = actions.create(RunReportAction.class, RunReportAction.ID);
runAllReportsAction.setTarget(departmentsTable);
runAllReports.setAction(runAllReportsAction);
```

You'll get the same result as for declarative definition.

**Comment by glebfox** [comment] 2021-03-01 11:48
Will be introduced in https://github.com/Haulmont/jmix-ui/issues/353

**Closed by glebfox** 2021-03-01 11:48 UTC
Labels: type: enhancement
