### ISSUE TITLE
NPE when trying to create or edit roles

### ISSUE THREAD

**Issue by natfirst** [cuba-platform/cuba#2199] opened 2019-06-17 08:54 UTC
#### Environment

- Platform version: 7.1, 7.2

#### Description of the bug or enhancement

- Open Roles screen
- Select an existing role for editing or try to create a new one

```
java.lang.NullPointerException
	at com.haulmont.cuba.gui.app.security.role.edit.tabs.ScreenPermissionsFrame.init(ScreenPermissionsFrame.java:110)
	at com.haulmont.cuba.gui.components.AbstractFrame.init(AbstractFrame.java:103)
	at com.haulmont.bali.events.EventHub.publish(EventHub.java:170)
	at com.haulmont.cuba.gui.screen.ScreenFragment.fireEvent(ScreenFragment.java:85)
	at com.haulmont.cuba.gui.screen.UiControllerUtils.fireEvent(UiControllerUtils.java:62)
	at com.haulmont.cuba.gui.sys.FragmentHelper$FragmentLoaderInitTask.execute(FragmentHelper.java:218)
	at com.haulmont.cuba.gui.xml.layout.loaders.ComponentLoaderContext.executeInitTasks(ComponentLoaderContext.java:178)
	at com.haulmont.cuba.web.sys.WebScreens.createScreen(WebScreens.java:250)
	at com.haulmont.cuba.web.sys.WebScreens.openEditor(WebScreens.java:1189)
	at com.haulmont.cuba.gui.components.HasWindowManager.openEditor(HasWindowManager.java:132)
	at com.haulmont.cuba.gui.components.actions.EditAction.internalOpenEditor(EditAction.java:287)
	at com.haulmont.cuba.gui.components.actions.EditAction.actionPerform(EditAction.java:231)
	at com.haulmont.cuba.web.gui.components.WebAbstractTable.handleClickAction(WebAbstractTable.java:1266)
	at com.haulmont.cuba.web.gui.components.WebAbstractTable.lambda$initComponent$db766529$1(WebAbstractTable.java:1038)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:496)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:273)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:237)
	at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1041)
	at com.vaadin.v7.ui.Table.handleClickEvent(Table.java:3126)
	at com.vaadin.v7.ui.Table.changeVariables(Table.java:2918)
	at com.haulmont.cuba.web.widgets.CubaTable.changeVariables(CubaTable.java:329)
	at com.vaadin.server.communication.ServerRpcHandler.changeVariables(ServerRpcHandler.java:611)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:457)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:400)
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:260)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:82)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1577)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:425)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.serviceAppRequest(CubaApplicationServlet.java:329)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.service(CubaApplicationServlet.java:215)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
```

**Comment by dtsaryov** [comment] 2019-06-17 09:42
Caused by #437. Will be fixed there

**Closed by dtsaryov** 2019-06-17 09:42 UTC
Labels: type: regression
