### ISSUE TITLE
Do not expose services for remote invocation in case of local service invocation deployment

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#635] opened 2017-11-23 14:25 UTC
Do not export services to Spring HTTP invoker in single war / single uber jar / local tomcat deployment

---
Original issue: https://youtrack.haulmont.com/issue/PL-10076

**Comment by knstvk** [comment] 2018-05-26 10:18
Duplicate of #506

**Closed by knstvk** 2018-05-26 10:18 UTC
Labels: type: enhancement
