### ISSUE TITLE
Add "openapi": "3.0" in swagger specification of Cuba's Rest API. Postman is unable to import Cuba Platform's REST specification (both json and yaml) right now

### ISSUE THREAD

**Issue by igor-korotkov** [cuba-platform/cuba#2963] opened 2020-07-14 09:06 UTC
Platform version: all
Client type: Portal

Postman is unable to import this:
{
  "swagger": "2.0",
  "info": {
    "version": "7.1",
    "title": "CUBA Platform REST API",
..............
}

But imports this just fine:
{
  "openapi": "3.0",
  "swagger": "2.0",
  "info": {
    "version": "7.1",
    "title": "CUBA Platform REST API",
...............
}

**Comment by gorbunkov** [comment] 2020-07-20 18:40
I guess postman couldn't import the yaml file because the file didn't fully conform the specification (the [issue](https://github.com/cuba-platform/restapi/issues/97)). The issue is just fixed and the latest version of file (e.g. from the master branch) should be imported without problems. You may [try it out](https://github.com/cuba-platform/restapi/blob/master/modules/rest-api/src/com/haulmont/addon/restapi/api/rest-api-swagger.yaml).

As for using the OpenAPI 3.0 specification, there is already an [issue](https://github.com/cuba-platform/restapi/issues/85) for that.

So I'm closing the current issue. @igor-korotkov let us know if there are any problems.

**Closed** 2020-07-20 18:40 UTC
Labels: type: enhancement
