### ISSUE TITLE
Related entities table aligned on right in the dialog mode

### ISSUE THREAD

**Issue by natfirst** [cuba-platform/cuba#2209] opened 2019-06-24 10:50 UTC
#### Environment

- Platform version: 7.0.6
- Forum issue: https://www.cuba-platform.com/discuss/t/table-moved-to-the-right-in-modal-dialogue/9303

#### Description of the bug or enhancement

- Create Organization and Employees entities
- In Organization add ONE_TO_MANY association with Employees
- Create browser and editor screen for Employees
- Create browser and editor screen for Organization:
   - set `@DialogMode(forceDialog = true)` for the Editor screen
   - Add  related table “Employees”
- Use the attached project to reproduce the issue

*A.R.* Relateb table move to the right in the dialog
![image.png](https://images.zenhubusercontent.com/5ae335564b5806bc2bd0e9cf/d4ba2f9f-5a45-4e99-8f34-d4a4b4b9bc07)

[demo.zip](https://app.zenhub.com/files/54624511/5fbde152-a195-4771-920c-f236415406a9/download)

**Comment by glebfox** [comment] 2019-07-19 09:53
The issue is caused by incorrect XML layout.

![image](https://user-images.githubusercontent.com/6077149/61526957-75042680-aa2c-11e9-9c8c-b9302c29f9fd.png)

After resolving all warnings the layout looks as intended.

**Closed by glebfox** 2019-07-19 09:53 UTC
Labels: state: won't fix, type: bug
