### ISSUE TITLE
Incorrect values are set to the component with options after commitAndClose action

### ISSUE THREAD

**Issue by Flaurite** [cuba-platform/cuba#1650] opened 2018-12-07 07:06 UTC
### Environment
- Platform version: 7.0.0
- Client type: Web

### Description of the bug or enhancement

Steps to reproduce:
1. Apply attached patch for refapp: 
[optionList.zip](https://github.com/cuba-platform/cuba/files/2657092/optionList.zip)

2. Create some `Repair` and `CarToken` instances (at least 2 CarTokens)
3. Open: _Application -> Screens v7 -> menu-config.DemoBrowse_
4. Select some repair (e.g repair1) and try to edit it
5. In the editor screen: select two values of CarToken and save it.
6. Edit this repair (repair1) again. Try to select one item of CarToken. And save it. 
After closing you will see "Value changed" notification.
- Expected behavior
`Value changed` event shouldn't be invoked
- Actual behavior
If you use debug you will see that after commit action will be invoked `setValue()` of `WebOptionList` and it takes list of 2 items instead of 1.

**Comment by jreznot** [comment] 2018-12-12 16:06
The main problem is:
> If you use debug you will see that after commit action will be invoked setValue() of WebOptionList and it takes list of 2 items instead of 1.

**Comment by knstvk** [comment] 2018-12-19 16:16
Cannot reproduce, probably fixed in 92e010e6e7450e3d08066413fa88d9c3a7935d3c

**Closed** 2018-12-25 12:46 UTC
Labels: client: web, state: fixed, type: bug, ver: 7.0.0
