### ISSUE TITLE
Entity not enhanced in project with groovy

### ISSUE THREAD

**Issue by zaharchenko-evgeny** [cuba-platform/cuba#2616] opened 2019-12-25 14:36 UTC
### Environment

- Platform version: 7.2

### Description of the bug or enhancement

Enhanced entities were replaced with not enhanced versions in `modules\global\build\classes\main` directory

Steps to reproduce the issue:
1. Create a new project on CUBA 7.1 without groovy support
2. Migrate a project to CUBA 7.2-SNAPSHOT via CUBA studio (V13-SNAPSHOT)
3. Enable `groovy` support in project properties
4. Create a new entity
5. Run `gradlew clean assemble` command
6. check decompiled classes in `modules\global\build\classes\main` directory

**Comment by dtsaryov** [comment] 2019-12-26 13:49
Caused by cuba-platform/cuba-gradle-plugin#60.

Will be fixed in Gradle plugin

**Closed by dtsaryov** 2019-12-26 13:49 UTC
Labels: type: bug
