### ISSUE TITLE
Highlight empty required fields and show validation errors

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/cuba#1119] opened 2018-08-05 07:29 UTC
Restore error highlighting for fields

**Comment by glebfox** [comment] 2018-08-27 07:34
Components that don't display highlight (but it's OK):
* `CheckBoxGroup`
* `OptionsGroup`
* `RadioButtonGroup`
* `DatePicker`

Components that don't display required indicator:
* `CurrencuField` - wasn't migrated to Vaadin 8 

Components that don't yet need to be tested:
* `TokenList` - wasn't migrated to Vaadin 8

**Comment by sukhova** [comment] 2018-09-03 14:14
Some components are no longer highlighted after you enter the information and then erase it

![test](https://user-images.githubusercontent.com/40686909/44991330-cd613f80-afa4-11e8-87b4-c94d19570cf5.gif)

Components with this behavior:

1) TextField
2) PasswordField
3) MaskedField
4) TextArea
5) RichEditArea
6) FieldGroup

**Comment by sukhova** [comment] 2018-09-03 14:35
All components except OptionsList and TwinColumn show "null" in notifications when required="true" but there is no attribute requiredMessage

**Comment by sukhova** [comment] 2018-09-03 14:39
Component TwinColumn shows highlighting if you specify both attributes required="true" and requiredMessage

**Comment by glebfox** [comment] 2018-09-04 10:47
@sukhova 

> Components with this behavior:
TextField
PasswordField
MaskedField
TextArea
RichEditArea

Fixed

> All components except OptionsList and TwinColumn show "null" in notifications when required="true" but there is no attribute requiredMessage.
OptionsList shows the blank notification.

Please, create a separate issue as this doesn't related to the components required indication. The screens validation logic should be fixed.

> Component TwinColumn shows highlighting if you specify both attributes required="true" and requiredMessage

Please, create a separate issue, because this component has not yet been migrated to Vaadin 8.

**Comment by sukhova** [comment] 2018-09-14 11:26
The MaskedField component is no longer highlighted after you enter the information and then erase it

![maskedfield](https://user-images.githubusercontent.com/40686909/45547628-74aa6600-b832-11e8-8c82-6db364e04660.gif)

**Comment by sukhova** [comment] 2018-09-14 11:52
FieldGroup component:

1) set required=”true”and set a value for the attribute “requiredMessage” in the field element
2) run the app and input some value in this field

**Expected behavior**
Required message is not displayed anymore
**Actual behavior**
Required message is displayed

You can see this behavior in _UserEditor_ with the “Login” field

![user](https://user-images.githubusercontent.com/40686909/45548639-1a130900-b836-11e8-8cb6-3b6acf7d6087.gif)

**Closed** 2018-09-19 08:14 UTC
Labels: client: web, state: fixed, type: regression, ver: 7.0.0
